python skills/generate-card/scripts/card_compositor.py \
  --template backgrounds/purple.png \
  --overlay buildings/it-kompaniya.png \
  --title-icon icons/purple-tower.png \
  --shadow \
  --output cards/it-kompaniya.png \
  --x-frac 0.54 \
  --y-frac 0.51 \
  --scale 0.62 \
  --coin-number 7 \
  --activation-number 6 \
  --title 'IT компания' \
  --title-color '#3E1F59' \
  --bottom-text $'Получите 5 монет из банка.\nВ свой ход.' \
  --bottom-text-y-frac 0.82 \
  --bottom-text-spacing-px 6 \
  --title-font fonts/Boingster-Regular.ttf \
  --title-font-size-frac 0.078 \
  --title-icon-scale 2.25 \
  --title-icon-gap-px 12 \
  --title-icon-y-offset-px -10 \
  --bottom-text-font fonts/CCUltimatum-Bold.ttf \
  --bottom-text-font-size-frac 0.05 \
  --activation-font fonts/Boingster-Regular.ttf \
  --activation-font-size-frac 0.118 \
  --coin-font fonts/Boingster-Regular.ttf
