python skills/generate-card/scripts/card_compositor.py \
  --template backgrounds/blue.png \
  --overlay buildings/novostroyka-03-pik-bashni.png \
  --title-icon icons/house.png \
  --shadow \
  --output cards/novostroyka-03-pik-bashni.png \
  --x-frac 0.50 \
  --y-frac 0.505 \
  --scale 0.3726 \
  --coin-number 3 \
  --activation-number 10 \
  --title 'Новостройка' \
  --title-color '#123E70' \
  --bottom-text $'Возьмите 3 монеты за ЖКХ\nВ ход любого игрока.' \
  --bottom-text-y-frac 0.83 \
  --bottom-text-spacing-px 6 \
  --title-font fonts/Boingster-Regular.ttf \
  --title-font-size-frac 0.065 \
  --bottom-text-font fonts/CCUltimatum-Bold.ttf \
  --bottom-text-font-size-frac 0.045 \
  --activation-font fonts/Boingster-Regular.ttf \
  --activation-font-size-frac 0.1 \
  --coin-font fonts/Boingster-Regular.ttf
