python skills/generate-card/scripts/card_compositor.py \
  --template backgrounds/blue.png \
  --overlay buildings/panelka.png \
  --title-icon icons/house.png \
  --shadow \
  --output cards/panelka.png \
  --x-frac 0.53 \
  --y-frac 0.51 \
  --scale 0.68 \
  --flip-horizontal \
  --coin-number 1 \
  --activation-number 1 \
  --title 'Панелька' \
  --title-color '#123E70' \
  --bottom-text $'Возьмите 1 монету за ЖКХ.\nВ ход любого игрока' \
  --bottom-text-y-frac 0.83 \
  --bottom-text-spacing-px 6 \
  --title-font fonts/Boingster-Regular.ttf \
  --title-font-size-frac 0.065 \
  --bottom-text-font fonts/CCUltimatum-Bold.ttf \
  --bottom-text-font-size-frac 0.045 \
  --activation-font fonts/Boingster-Regular.ttf \
  --activation-font-size-frac 0.1 \
  --coin-font fonts/Boingster-Regular.ttf
