.venv/bin/python skills/generate-card/scripts/card_compositor.py \
  --template backgrounds/green.png \
  --overlay buildings/pivnoy-laryok-05-futbol-v3.png \
  --title-icon icons/shop-stall.png \
  --shadow \
  --output cards/pivnoy-laryok-05-futbol-v3.png \
  --x-frac 0.50 \
  --y-frac 0.5250 \
  --scale 0.6027 \
  --coin-number 1 \
  --activation-number '2-3' \
  --title 'Пивной ларёк' \
  --title-color '#17361A' \
  --bottom-text $'Возьмите 1 монету из банка.\nВ свой ход.' \
  --bottom-text-y-frac 0.82 \
  --bottom-text-spacing-px 6 \
  --title-font fonts/Boingster-Regular.ttf \
  --title-font-size-frac 0.078 \
  --title-icon-scale 2.25 \
  --title-icon-gap-px 12 \
  --title-icon-y-offset-px -10 \
  --bottom-text-font fonts/CCUltimatum-Bold.ttf \
  --bottom-text-font-size-frac 0.0477 \
  --activation-font fonts/Boingster-Regular.ttf \
  --activation-font-size-frac 0.118 \
  --coin-font fonts/Boingster-Regular.ttf
