python skills/generate-card/scripts/card_compositor.py \
  --template backgrounds/red.png \
  --overlay buildings/shwarma-03-zima-v3.png \
  --title-icon icons/shwarma.png \
  --shadow \
  --output cards/shwarma-03-zima-v3.png \
  --x-frac 0.50 \
  --y-frac 0.52 \
  --scale 0.60 \
  --coin-number 2 \
  --activation-number 3 \
  --title 'Шавуха' \
  --title-color '#58100E' \
  --bottom-text $'Возьмите 1 монету у голодного игрока,\nбросившего кубики\nВ ход другого игрока.' \
  --bottom-text-y-frac 0.81 \
  --bottom-text-spacing-px 6 \
  --title-font fonts/Boingster-Regular.ttf \
  --title-font-size-frac 0.078 \
  --title-icon-scale 2.25 \
  --title-icon-gap-px 12 \
  --title-icon-y-offset-px -10 \
  --bottom-text-font fonts/CCUltimatum-Bold.ttf \
  --bottom-text-font-size-frac 0.0389 \
  --activation-font fonts/CCUltimatum-Bold.ttf \
  --activation-font-size-frac 0.118 \
  --coin-font fonts/Boingster-Regular.ttf
